name: "Exemplo de CD"

on:
  pull_request:
    branches:
      - hml

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull gustavodessunte/ci-example:latest

      - name: Stop Docker container
        run: docker stop ci-example || true

      - name: Remove Docker container
        run: docker rm ci-example || true

      - name: Run Docker container
        run: docker run --name ci-example -d -p 8080:8080 gustavodessunte/ci-example:latest