# é necessário criar as variáveis DEPLOY_HOST, DEPLOY_KEY, NOME_ARQUIVO_PEM e NOME_ARQUIVO_JAR.
# Settings -> Secrets and Variables -> Actions
#  New Respository Secret ou editar as existentes (NÃO é possível ver o valor das existentes!)

# OBS: neste exeplo estamos considerando que a mesma chave .pem permite acessar as ec2 pública e privada
name: CI/CD para Spring Boot com Maven e publicação em EC2

# este arquivo será executado numa VM do github
on:
  pull_request:
    branches: #branch 'alvo'. Ou seja, se algo mudar nela, a mínima mudança que seja, este arquivo de workflow será executado
      - hml

jobs: # cada 'job' é um agrupamento de steps
  build: # primeiro grupo de steps
    runs-on: ubuntu-latest # aqui apenas indicamos onde o workflow será executado (em qual tipo de VM). No caso indicamos que será num ubuntu. Isso NÃO tem relação com o SO de sua EC2!

    steps: # cada 'step' é uma ação dentro de um grupo de steps
    - name: Atualização do código
      uses: actions/checkout@v2 # action que leva para a VM de execução do workflow os arquivos da branch alvo

    - name: Definindo a versão da JDK 
      uses: actions/setup-java@v2 # configura na VM uma versão do Java
      with:
        distribution: 'temurin' # ver opções em https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
        java-version: '17'

    - name: Build com Maven
      run: mvn -X -e -f api_MiseEnPlace/pom.xml clean package
      # com 'run' podemos executar qualquer comando de SO na VM de execução do workflow.
      # nesse caso, pedimos para gerar o .jar de uma aplicação Java
      # tivemos que fazer -f <caminho do pom> porque o projeto Java não está na raiz do repositório

    - name: Gerar artefato Github com o .jar gerado
      uses: actions/upload-artifact@v4 # essa action promove o envio de um ou mais arquivos para uma pasta temporária do github actions
      with:
        name: aplicacao # nome do arquivo ou conjunto de arquivos (veja ele depois em 'Recuperar jars')
        path: api_MiseEnPlace/target/*.jar # todos os arquivos .jar do diretório api-pets-completa/target

    - name: Gerar artefato Github com os arquivos .sh
      uses: actions/upload-artifact@v4        
      with:
        name: scripts  # nome do arquivo ou conjunto de arquivos (veja ele depois em 'Recuperar scripts')
        path: .github/scripts/*.sh # todos os arquivos .sh do diretório .github/scripts

  deploy:
    needs: build # segundo grupo de steps
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar jars
      uses: actions/download-artifact@v4  # essa action promove o download de um ou mais arquivos de uma pasta temporária do github actions
      with:
        name: aplicacao # nome do arquivo ou conjunto de arquivos que queremos recuperar
        path: ./ # diretório da VM de execução do workflow onde os arquivos recuperados ficarão

    - name: Recuperar scripts
      uses: actions/download-artifact@v4
      with:
        name: scripts
        path: ./        

    - name: Criar arquivo .pem a partir da variável DEPLOY_KEY e fazer o chmod 400 nele
      id: geracao-arquivo-pem # o id é opcional, mas é bom para fins de log
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
        chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
      # aqui geramos um arquivo .pem a partir de seu conteúdo (que é apenas um arquivo texto)  

    - name: Enviar o JAR p/ a EC2
      uses: appleboy/scp-action@master # esta action abstrai o uso do comando scp, permitindo o envio de arquivos via ssh
      with:
        host: ${{ secrets.DEPLOY_HOST }} # ip da ec2 pública
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }} # conteúdo pem que permite acesso à ec2 pública
        source: "./*.jar" # enviando todos os .jar (estão lá graças ao step 'Recuperar jars')
        target: "/home/ubuntu/deploy-api/" # diretório de destino na ec2 pública

    - name: Enviar os Scripts p/ a EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "./*.sh"  # enviando todos os .jar (estão lá graças ao step 'Recuperar scripts')
        target: "/home/ubuntu/deploy-api/" # diretório de destino na ec2 pública

    - name: Conectar via SSH à EC2 privada para implantar e reiniciar a API
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.DEPLOY_HOST }} '
          scp -i ${{ secrets.NOME_ARQUIVO_PEM }} deploy-api/${{ secrets.NOME_ARQUIVO_JAR }} ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api
          scp -i ${{ secrets.NOME_ARQUIVO_PEM }} deploy-api/*.sh ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api
          ssh -i ${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.IP_PRIVADO_EC2 }} "sh /home/ubuntu/deploy-api/api-restart.sh"          
        '
      # aqui nós nos conectamos via SSH na ec2 pública e, nela, executamos 3 comandos:
      # 1. copiamos o arquivo .jar para a ec2 privada
      # 2. copiamos os arquivos .sh para a ec2 privada
      # 3. pedimos a execução de um dos arquivos .sh recém copiados para a ec2 privad
      # os passos #1 a #3 poderiam estar num script sh. Fiz assim para mostrar outra forma de executar comandos via github actions 
