name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - hml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualização do código
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipRepositoryChecks

      - name: Gerar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao
          path: api_MiseEnPlace/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar artefatos
        uses: actions/download-artifact@v4
        with:
          name: aplicacao
          path: ./

      - name: Gerar arquivo .pem
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}

      - name: Enviar arquivos para EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./*.jar"
          target: "/home/ubuntu/deploy-api/"

      - name: Implantar na EC2 privada
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.DEPLOY_HOST }} "
            bash /home/ubuntu/deploy-api/deploy-to-private-ec2.sh"
